import { readFileSync } from "node:fs";
import { connectOffloadProvider } from "../vendor/pocketjs/tools/offload-provider.ts";
const required=(name:string)=>{const v=process.env[name];if(!v)throw new Error(`Set ${name} in .env (see .env.example)`);return v;};
const ipv4=(v:string)=>/^\d{1,3}(\.\d{1,3}){3}$/.test(v)&&v.split(".").every(n=>Number(n)<=255);
const address=required("DEVICE_IP"),advertiseHost=required("COMPANION_IP");
if(!ipv4(address)||!ipv4(advertiseHost)||advertiseHost.startsWith("127."))throw new Error("Use reachable numeric LAN IPv4 addresses");
const mediaPort=Number(process.env.MEDIA_PORT??8742);
if(!Number.isInteger(mediaPort)||mediaPort<1024||mediaPort>65535)throw new Error("Invalid MEDIA_PORT");
const key=readFileSync(".pocket/offload.key","utf8").trim();
if(!/^[0-9a-f]{64}$/.test(key))throw new Error("Run bun run pair first");
if(!Bun.which("ffmpeg"))throw new Error("Install FFmpeg with libx264 and add it to PATH");
const data={advertiseHost,mediaPort,url:required("JELLYFIN_URL"),username:required("JELLYFIN_USERNAME"),password:required("JELLYFIN_PASSWORD"),deviceId:`jellyfin3ds-${address.replaceAll(".","-")}`};
const provider=connectOffloadProvider({address,key,worker:new URL("./worker.ts",import.meta.url),data,log:console.log});
console.log(`Jellyfin3DS companion connecting to ${address}:8741; media on ${advertiseHost}:${mediaPort}`);
for(const signal of ["SIGINT","SIGTERM"] as const)process.on(signal,()=>{provider.close();process.exit();});
